name:                HaskGuard
version:             0.1
github:              "ngirot/HaskGuard"
license:             BSD-3-Clause
author:              "Nicolas Girot"
maintainer:          "ngirot@hotmail.com"
copyright:           "2024 Nicolas Girot"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ngirot/HaskGuard#readme>

dependencies:
- base >= 4.7 && < 5
- network == 3.1.4.0
- bytestring == 0.11.5.3
ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  HaskGuard-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HaskGuard

tests:
  HaskGuard-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec >=2.11.9
    - HaskGuard
